### ISSUE TITLE
$ only designation of variable names is a little limiting

### ISSUE THREAD

**Issue by youngamichael** [abe-winter/varyaml#2]
Nice project.  I'd like to use it. However the $ENV_NAME might be too limiting for my use case.  I have a simple yaml file that I would like to inject environment variables in.  The problem is if I want to inject them mid string, like a db connection string for example, there is no way for the parser to tell where my placholder ends.  

Example:
db_connection: mysql+pymysql://$MYSQL_USER:$MYSQL_PASS@servername:3306/

If it could parse this as well ${MYSQL_USER} then it would work.  Is this possible in the current implementation?

**Comment by abe-winter** [comment]
Nope, it can't interpolate like that -- that would require more parsing =
more moving parts. You should investigate lbolla/yamlenv

**Comment by youngamichael** [comment]
Yeah.  Thanks for the suggestion but I found a solution using ruamel-yaml.  Turns out you should be able to do this type of interpolation with pyaml but a bug was introduced in 5.x which renders most of the solutions hooking into the pyaml process useless.
